// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/host_agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostAgent_CreateCell_FullMethodName     = "/oncell.hostagent.HostAgent/CreateCell"
	HostAgent_StartCell_FullMethodName      = "/oncell.hostagent.HostAgent/StartCell"
	HostAgent_PauseCell_FullMethodName      = "/oncell.hostagent.HostAgent/PauseCell"
	HostAgent_ResumeCell_FullMethodName     = "/oncell.hostagent.HostAgent/ResumeCell"
	HostAgent_DeleteCell_FullMethodName     = "/oncell.hostagent.HostAgent/DeleteCell"
	HostAgent_GetCellStatus_FullMethodName  = "/oncell.hostagent.HostAgent/GetCellStatus"
	HostAgent_SnapshotCell_FullMethodName   = "/oncell.hostagent.HostAgent/SnapshotCell"
	HostAgent_ListCells_FullMethodName      = "/oncell.hostagent.HostAgent/ListCells"
	HostAgent_GetHostMetrics_FullMethodName = "/oncell.hostagent.HostAgent/GetHostMetrics"
)

// HostAgentClient is the client API for HostAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostAgentClient interface {
	CreateCell(ctx context.Context, in *CreateCellRequest, opts ...grpc.CallOption) (*CellResponse, error)
	StartCell(ctx context.Context, in *CellId, opts ...grpc.CallOption) (*CellResponse, error)
	PauseCell(ctx context.Context, in *CellId, opts ...grpc.CallOption) (*CellResponse, error)
	ResumeCell(ctx context.Context, in *CellId, opts ...grpc.CallOption) (*CellResponse, error)
	DeleteCell(ctx context.Context, in *CellId, opts ...grpc.CallOption) (*CellResponse, error)
	GetCellStatus(ctx context.Context, in *CellId, opts ...grpc.CallOption) (*CellResponse, error)
	SnapshotCell(ctx context.Context, in *CellId, opts ...grpc.CallOption) (*SnapshotResponse, error)
	ListCells(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCellsResponse, error)
	GetHostMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HostMetrics, error)
}

type hostAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewHostAgentClient(cc grpc.ClientConnInterface) HostAgentClient {
	return &hostAgentClient{cc}
}

func (c *hostAgentClient) CreateCell(ctx context.Context, in *CreateCellRequest, opts ...grpc.CallOption) (*CellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CellResponse)
	err := c.cc.Invoke(ctx, HostAgent_CreateCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) StartCell(ctx context.Context, in *CellId, opts ...grpc.CallOption) (*CellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CellResponse)
	err := c.cc.Invoke(ctx, HostAgent_StartCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) PauseCell(ctx context.Context, in *CellId, opts ...grpc.CallOption) (*CellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CellResponse)
	err := c.cc.Invoke(ctx, HostAgent_PauseCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) ResumeCell(ctx context.Context, in *CellId, opts ...grpc.CallOption) (*CellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CellResponse)
	err := c.cc.Invoke(ctx, HostAgent_ResumeCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) DeleteCell(ctx context.Context, in *CellId, opts ...grpc.CallOption) (*CellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CellResponse)
	err := c.cc.Invoke(ctx, HostAgent_DeleteCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) GetCellStatus(ctx context.Context, in *CellId, opts ...grpc.CallOption) (*CellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CellResponse)
	err := c.cc.Invoke(ctx, HostAgent_GetCellStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) SnapshotCell(ctx context.Context, in *CellId, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, HostAgent_SnapshotCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) ListCells(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCellsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCellsResponse)
	err := c.cc.Invoke(ctx, HostAgent_ListCells_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostAgentClient) GetHostMetrics(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HostMetrics, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostMetrics)
	err := c.cc.Invoke(ctx, HostAgent_GetHostMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostAgentServer is the server API for HostAgent service.
// All implementations must embed UnimplementedHostAgentServer
// for forward compatibility.
type HostAgentServer interface {
	CreateCell(context.Context, *CreateCellRequest) (*CellResponse, error)
	StartCell(context.Context, *CellId) (*CellResponse, error)
	PauseCell(context.Context, *CellId) (*CellResponse, error)
	ResumeCell(context.Context, *CellId) (*CellResponse, error)
	DeleteCell(context.Context, *CellId) (*CellResponse, error)
	GetCellStatus(context.Context, *CellId) (*CellResponse, error)
	SnapshotCell(context.Context, *CellId) (*SnapshotResponse, error)
	ListCells(context.Context, *Empty) (*ListCellsResponse, error)
	GetHostMetrics(context.Context, *Empty) (*HostMetrics, error)
	mustEmbedUnimplementedHostAgentServer()
}

// UnimplementedHostAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostAgentServer struct{}

func (UnimplementedHostAgentServer) CreateCell(context.Context, *CreateCellRequest) (*CellResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCell not implemented")
}
func (UnimplementedHostAgentServer) StartCell(context.Context, *CellId) (*CellResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartCell not implemented")
}
func (UnimplementedHostAgentServer) PauseCell(context.Context, *CellId) (*CellResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseCell not implemented")
}
func (UnimplementedHostAgentServer) ResumeCell(context.Context, *CellId) (*CellResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeCell not implemented")
}
func (UnimplementedHostAgentServer) DeleteCell(context.Context, *CellId) (*CellResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCell not implemented")
}
func (UnimplementedHostAgentServer) GetCellStatus(context.Context, *CellId) (*CellResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCellStatus not implemented")
}
func (UnimplementedHostAgentServer) SnapshotCell(context.Context, *CellId) (*SnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SnapshotCell not implemented")
}
func (UnimplementedHostAgentServer) ListCells(context.Context, *Empty) (*ListCellsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCells not implemented")
}
func (UnimplementedHostAgentServer) GetHostMetrics(context.Context, *Empty) (*HostMetrics, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHostMetrics not implemented")
}
func (UnimplementedHostAgentServer) mustEmbedUnimplementedHostAgentServer() {}
func (UnimplementedHostAgentServer) testEmbeddedByValue()                   {}

// UnsafeHostAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostAgentServer will
// result in compilation errors.
type UnsafeHostAgentServer interface {
	mustEmbedUnimplementedHostAgentServer()
}

func RegisterHostAgentServer(s grpc.ServiceRegistrar, srv HostAgentServer) {
	// If the following call panics, it indicates UnimplementedHostAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostAgent_ServiceDesc, srv)
}

func _HostAgent_CreateCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).CreateCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_CreateCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).CreateCell(ctx, req.(*CreateCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_StartCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).StartCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_StartCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).StartCell(ctx, req.(*CellId))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_PauseCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).PauseCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_PauseCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).PauseCell(ctx, req.(*CellId))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_ResumeCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).ResumeCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_ResumeCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).ResumeCell(ctx, req.(*CellId))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_DeleteCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).DeleteCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_DeleteCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).DeleteCell(ctx, req.(*CellId))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_GetCellStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).GetCellStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_GetCellStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).GetCellStatus(ctx, req.(*CellId))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_SnapshotCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).SnapshotCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_SnapshotCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).SnapshotCell(ctx, req.(*CellId))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_ListCells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).ListCells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_ListCells_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).ListCells(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostAgent_GetHostMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).GetHostMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_GetHostMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).GetHostMetrics(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// HostAgent_ServiceDesc is the grpc.ServiceDesc for HostAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oncell.hostagent.HostAgent",
	HandlerType: (*HostAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCell",
			Handler:    _HostAgent_CreateCell_Handler,
		},
		{
			MethodName: "StartCell",
			Handler:    _HostAgent_StartCell_Handler,
		},
		{
			MethodName: "PauseCell",
			Handler:    _HostAgent_PauseCell_Handler,
		},
		{
			MethodName: "ResumeCell",
			Handler:    _HostAgent_ResumeCell_Handler,
		},
		{
			MethodName: "DeleteCell",
			Handler:    _HostAgent_DeleteCell_Handler,
		},
		{
			MethodName: "GetCellStatus",
			Handler:    _HostAgent_GetCellStatus_Handler,
		},
		{
			MethodName: "SnapshotCell",
			Handler:    _HostAgent_SnapshotCell_Handler,
		},
		{
			MethodName: "ListCells",
			Handler:    _HostAgent_ListCells_Handler,
		},
		{
			MethodName: "GetHostMetrics",
			Handler:    _HostAgent_GetHostMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/host_agent.proto",
}
