// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: host_agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_host_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_host_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_host_agent_proto_rawDescGZIP(), []int{0}
}

type CellId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellId        string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellId) Reset() {
	*x = CellId{}
	mi := &file_host_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellId) ProtoMessage() {}

func (x *CellId) ProtoReflect() protoreflect.Message {
	mi := &file_host_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellId.ProtoReflect.Descriptor instead.
func (*CellId) Descriptor() ([]byte, []int) {
	return file_host_agent_proto_rawDescGZIP(), []int{1}
}

func (x *CellId) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

type CellSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuMillicores int32                  `protobuf:"varint,1,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"` // 4000 = 4 cores
	MemoryMb      int32                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`                // 8192 = 8 GB
	StorageGb     int32                  `protobuf:"varint,3,opt,name=storage_gb,json=storageGb,proto3" json:"storage_gb,omitempty"`             // 50 = 50 GB
	Packages      []string               `protobuf:"bytes,4,rep,name=packages,proto3" json:"packages,omitempty"`
	Network       *NetworkConfig         `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellSpec) Reset() {
	*x = CellSpec{}
	mi := &file_host_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellSpec) ProtoMessage() {}

func (x *CellSpec) ProtoReflect() protoreflect.Message {
	mi := &file_host_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellSpec.ProtoReflect.Descriptor instead.
func (*CellSpec) Descriptor() ([]byte, []int) {
	return file_host_agent_proto_rawDescGZIP(), []int{2}
}

func (x *CellSpec) GetCpuMillicores() int32 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *CellSpec) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *CellSpec) GetStorageGb() int32 {
	if x != nil {
		return x.StorageGb
	}
	return 0
}

func (x *CellSpec) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *CellSpec) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

type NetworkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Egress        string                 `protobuf:"bytes,1,opt,name=egress,proto3" json:"egress,omitempty"` // "blocked" or "open"
	Allow         []string               `protobuf:"bytes,2,rep,name=allow,proto3" json:"allow,omitempty"`   // ["github.com", "api.openai.com"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_host_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_host_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_host_agent_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkConfig) GetEgress() string {
	if x != nil {
		return x.Egress
	}
	return ""
}

func (x *NetworkConfig) GetAllow() []string {
	if x != nil {
		return x.Allow
	}
	return nil
}

type CreateCellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellId        string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	DeveloperId   string                 `protobuf:"bytes,3,opt,name=developer_id,json=developerId,proto3" json:"developer_id,omitempty"`
	Spec          *CellSpec              `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	AgentImage    string                 `protobuf:"bytes,5,opt,name=agent_image,json=agentImage,proto3" json:"agent_image,omitempty"`
	Config        map[string]string      `protobuf:"bytes,6,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`   // customer config
	Secrets       map[string]string      `protobuf:"bytes,7,rep,name=secrets,proto3" json:"secrets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // encrypted secrets
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCellRequest) Reset() {
	*x = CreateCellRequest{}
	mi := &file_host_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCellRequest) ProtoMessage() {}

func (x *CreateCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_host_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCellRequest.ProtoReflect.Descriptor instead.
func (*CreateCellRequest) Descriptor() ([]byte, []int) {
	return file_host_agent_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCellRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *CreateCellRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateCellRequest) GetDeveloperId() string {
	if x != nil {
		return x.DeveloperId
	}
	return ""
}

func (x *CreateCellRequest) GetSpec() *CellSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CreateCellRequest) GetAgentImage() string {
	if x != nil {
		return x.AgentImage
	}
	return ""
}

func (x *CreateCellRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateCellRequest) GetSecrets() map[string]string {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type CellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellId        string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	Status        *CellStatus            `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellResponse) Reset() {
	*x = CellResponse{}
	mi := &file_host_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellResponse) ProtoMessage() {}

func (x *CellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_host_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellResponse.ProtoReflect.Descriptor instead.
func (*CellResponse) Descriptor() ([]byte, []int) {
	return file_host_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CellResponse) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *CellResponse) GetStatus() *CellStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CellResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CellResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CellStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellId        string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // "creating", "active", "paused", "deleted"
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActiveAt  int64                  `protobuf:"varint,5,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	PausedAt      int64                  `protobuf:"varint,6,opt,name=paused_at,json=pausedAt,proto3" json:"paused_at,omitempty"`
	Resources     *CellResourceUsage     `protobuf:"bytes,7,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellStatus) Reset() {
	*x = CellStatus{}
	mi := &file_host_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellStatus) ProtoMessage() {}

func (x *CellStatus) ProtoReflect() protoreflect.Message {
	mi := &file_host_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellStatus.ProtoReflect.Descriptor instead.
func (*CellStatus) Descriptor() ([]byte, []int) {
	return file_host_agent_proto_rawDescGZIP(), []int{6}
}

func (x *CellStatus) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *CellStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CellStatus) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CellStatus) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CellStatus) GetLastActiveAt() int64 {
	if x != nil {
		return x.LastActiveAt
	}
	return 0
}

func (x *CellStatus) GetPausedAt() int64 {
	if x != nil {
		return x.PausedAt
	}
	return 0
}

func (x *CellStatus) GetResources() *CellResourceUsage {
	if x != nil {
		return x.Resources
	}
	return nil
}

type CellResourceUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	StorageBytes  int64                  `protobuf:"varint,3,opt,name=storage_bytes,json=storageBytes,proto3" json:"storage_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellResourceUsage) Reset() {
	*x = CellResourceUsage{}
	mi := &file_host_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellResourceUsage) ProtoMessage() {}

func (x *CellResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_host_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellResourceUsage.ProtoReflect.Descriptor instead.
func (*CellResourceUsage) Descriptor() ([]byte, []int) {
	return file_host_agent_proto_rawDescGZIP(), []int{7}
}

func (x *CellResourceUsage) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *CellResourceUsage) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *CellResourceUsage) GetStorageBytes() int64 {
	if x != nil {
		return x.StorageBytes
	}
	return 0
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellId        string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	SnapshotPath  string                 `protobuf:"bytes,2,opt,name=snapshot_path,json=snapshotPath,proto3" json:"snapshot_path,omitempty"` // S3 path
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_host_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_host_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_host_agent_proto_rawDescGZIP(), []int{8}
}

func (x *SnapshotResponse) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *SnapshotResponse) GetSnapshotPath() string {
	if x != nil {
		return x.SnapshotPath
	}
	return ""
}

func (x *SnapshotResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type ListCellsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*CellStatus          `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCellsResponse) Reset() {
	*x = ListCellsResponse{}
	mi := &file_host_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCellsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCellsResponse) ProtoMessage() {}

func (x *ListCellsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_host_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCellsResponse.ProtoReflect.Descriptor instead.
func (*ListCellsResponse) Descriptor() ([]byte, []int) {
	return file_host_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ListCellsResponse) GetCells() []*CellStatus {
	if x != nil {
		return x.Cells
	}
	return nil
}

type HostMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CpuTotalMillicores int32                  `protobuf:"varint,1,opt,name=cpu_total_millicores,json=cpuTotalMillicores,proto3" json:"cpu_total_millicores,omitempty"`
	CpuUsedMillicores  int32                  `protobuf:"varint,2,opt,name=cpu_used_millicores,json=cpuUsedMillicores,proto3" json:"cpu_used_millicores,omitempty"`
	MemoryTotalBytes   int64                  `protobuf:"varint,3,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	MemoryUsedBytes    int64                  `protobuf:"varint,4,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	StorageTotalBytes  int64                  `protobuf:"varint,5,opt,name=storage_total_bytes,json=storageTotalBytes,proto3" json:"storage_total_bytes,omitempty"`
	StorageUsedBytes   int64                  `protobuf:"varint,6,opt,name=storage_used_bytes,json=storageUsedBytes,proto3" json:"storage_used_bytes,omitempty"`
	ActiveCells        int32                  `protobuf:"varint,7,opt,name=active_cells,json=activeCells,proto3" json:"active_cells,omitempty"`
	PausedCells        int32                  `protobuf:"varint,8,opt,name=paused_cells,json=pausedCells,proto3" json:"paused_cells,omitempty"`
	CachedCustomers    []string               `protobuf:"bytes,9,rep,name=cached_customers,json=cachedCustomers,proto3" json:"cached_customers,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HostMetrics) Reset() {
	*x = HostMetrics{}
	mi := &file_host_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMetrics) ProtoMessage() {}

func (x *HostMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_host_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMetrics.ProtoReflect.Descriptor instead.
func (*HostMetrics) Descriptor() ([]byte, []int) {
	return file_host_agent_proto_rawDescGZIP(), []int{10}
}

func (x *HostMetrics) GetCpuTotalMillicores() int32 {
	if x != nil {
		return x.CpuTotalMillicores
	}
	return 0
}

func (x *HostMetrics) GetCpuUsedMillicores() int32 {
	if x != nil {
		return x.CpuUsedMillicores
	}
	return 0
}

func (x *HostMetrics) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *HostMetrics) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *HostMetrics) GetStorageTotalBytes() int64 {
	if x != nil {
		return x.StorageTotalBytes
	}
	return 0
}

func (x *HostMetrics) GetStorageUsedBytes() int64 {
	if x != nil {
		return x.StorageUsedBytes
	}
	return 0
}

func (x *HostMetrics) GetActiveCells() int32 {
	if x != nil {
		return x.ActiveCells
	}
	return 0
}

func (x *HostMetrics) GetPausedCells() int32 {
	if x != nil {
		return x.PausedCells
	}
	return 0
}

func (x *HostMetrics) GetCachedCustomers() []string {
	if x != nil {
		return x.CachedCustomers
	}
	return nil
}

var File_host_agent_proto protoreflect.FileDescriptor

const file_host_agent_proto_rawDesc = "" +
	"\n" +
	"\x10host_agent.proto\x12\x10oncell.hostagent\"\a\n" +
	"\x05Empty\"!\n" +
	"\x06CellId\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\"\xc4\x01\n" +
	"\bCellSpec\x12%\n" +
	"\x0ecpu_millicores\x18\x01 \x01(\x05R\rcpuMillicores\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x05R\bmemoryMb\x12\x1d\n" +
	"\n" +
	"storage_gb\x18\x03 \x01(\x05R\tstorageGb\x12\x1a\n" +
	"\bpackages\x18\x04 \x03(\tR\bpackages\x129\n" +
	"\anetwork\x18\x05 \x01(\v2\x1f.oncell.hostagent.NetworkConfigR\anetwork\"=\n" +
	"\rNetworkConfig\x12\x16\n" +
	"\x06egress\x18\x01 \x01(\tR\x06egress\x12\x14\n" +
	"\x05allow\x18\x02 \x03(\tR\x05allow\"\xcd\x03\n" +
	"\x11CreateCellRequest\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\fdeveloper_id\x18\x03 \x01(\tR\vdeveloperId\x12.\n" +
	"\x04spec\x18\x04 \x01(\v2\x1a.oncell.hostagent.CellSpecR\x04spec\x12\x1f\n" +
	"\vagent_image\x18\x05 \x01(\tR\n" +
	"agentImage\x12G\n" +
	"\x06config\x18\x06 \x03(\v2/.oncell.hostagent.CreateCellRequest.ConfigEntryR\x06config\x12J\n" +
	"\asecrets\x18\a \x03(\v20.oncell.hostagent.CreateCellRequest.SecretsEntryR\asecrets\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fSecretsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\fCellResponse\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x124\n" +
	"\x06status\x18\x02 \x01(\v2\x1c.oncell.hostagent.CellStatusR\x06status\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xf4\x01\n" +
	"\n" +
	"CellStatus\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12$\n" +
	"\x0elast_active_at\x18\x05 \x01(\x03R\flastActiveAt\x12\x1b\n" +
	"\tpaused_at\x18\x06 \x01(\x03R\bpausedAt\x12A\n" +
	"\tresources\x18\a \x01(\v2#.oncell.hostagent.CellResourceUsageR\tresources\"|\n" +
	"\x11CellResourceUsage\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12#\n" +
	"\rstorage_bytes\x18\x03 \x01(\x03R\fstorageBytes\"o\n" +
	"\x10SnapshotResponse\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x12#\n" +
	"\rsnapshot_path\x18\x02 \x01(\tR\fsnapshotPath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\"G\n" +
	"\x11ListCellsResponse\x122\n" +
	"\x05cells\x18\x01 \x03(\v2\x1c.oncell.hostagent.CellStatusR\x05cells\"\x98\x03\n" +
	"\vHostMetrics\x120\n" +
	"\x14cpu_total_millicores\x18\x01 \x01(\x05R\x12cpuTotalMillicores\x12.\n" +
	"\x13cpu_used_millicores\x18\x02 \x01(\x05R\x11cpuUsedMillicores\x12,\n" +
	"\x12memory_total_bytes\x18\x03 \x01(\x03R\x10memoryTotalBytes\x12*\n" +
	"\x11memory_used_bytes\x18\x04 \x01(\x03R\x0fmemoryUsedBytes\x12.\n" +
	"\x13storage_total_bytes\x18\x05 \x01(\x03R\x11storageTotalBytes\x12,\n" +
	"\x12storage_used_bytes\x18\x06 \x01(\x03R\x10storageUsedBytes\x12!\n" +
	"\factive_cells\x18\a \x01(\x05R\vactiveCells\x12!\n" +
	"\fpaused_cells\x18\b \x01(\x05R\vpausedCells\x12)\n" +
	"\x10cached_customers\x18\t \x03(\tR\x0fcachedCustomers2\xaa\x05\n" +
	"\tHostAgent\x12Q\n" +
	"\n" +
	"CreateCell\x12#.oncell.hostagent.CreateCellRequest\x1a\x1e.oncell.hostagent.CellResponse\x12E\n" +
	"\tStartCell\x12\x18.oncell.hostagent.CellId\x1a\x1e.oncell.hostagent.CellResponse\x12E\n" +
	"\tPauseCell\x12\x18.oncell.hostagent.CellId\x1a\x1e.oncell.hostagent.CellResponse\x12F\n" +
	"\n" +
	"ResumeCell\x12\x18.oncell.hostagent.CellId\x1a\x1e.oncell.hostagent.CellResponse\x12F\n" +
	"\n" +
	"DeleteCell\x12\x18.oncell.hostagent.CellId\x1a\x1e.oncell.hostagent.CellResponse\x12I\n" +
	"\rGetCellStatus\x12\x18.oncell.hostagent.CellId\x1a\x1e.oncell.hostagent.CellResponse\x12L\n" +
	"\fSnapshotCell\x12\x18.oncell.hostagent.CellId\x1a\".oncell.hostagent.SnapshotResponse\x12I\n" +
	"\tListCells\x12\x17.oncell.hostagent.Empty\x1a#.oncell.hostagent.ListCellsResponse\x12H\n" +
	"\x0eGetHostMetrics\x12\x17.oncell.hostagent.Empty\x1a\x1d.oncell.hostagent.HostMetricsB:Z8github.com/oncellai/control-plane/internal/hostclient/pbb\x06proto3"

var (
	file_host_agent_proto_rawDescOnce sync.Once
	file_host_agent_proto_rawDescData []byte
)

func file_host_agent_proto_rawDescGZIP() []byte {
	file_host_agent_proto_rawDescOnce.Do(func() {
		file_host_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_host_agent_proto_rawDesc), len(file_host_agent_proto_rawDesc)))
	})
	return file_host_agent_proto_rawDescData
}

var file_host_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_host_agent_proto_goTypes = []any{
	(*Empty)(nil),             // 0: oncell.hostagent.Empty
	(*CellId)(nil),            // 1: oncell.hostagent.CellId
	(*CellSpec)(nil),          // 2: oncell.hostagent.CellSpec
	(*NetworkConfig)(nil),     // 3: oncell.hostagent.NetworkConfig
	(*CreateCellRequest)(nil), // 4: oncell.hostagent.CreateCellRequest
	(*CellResponse)(nil),      // 5: oncell.hostagent.CellResponse
	(*CellStatus)(nil),        // 6: oncell.hostagent.CellStatus
	(*CellResourceUsage)(nil), // 7: oncell.hostagent.CellResourceUsage
	(*SnapshotResponse)(nil),  // 8: oncell.hostagent.SnapshotResponse
	(*ListCellsResponse)(nil), // 9: oncell.hostagent.ListCellsResponse
	(*HostMetrics)(nil),       // 10: oncell.hostagent.HostMetrics
	nil,                       // 11: oncell.hostagent.CreateCellRequest.ConfigEntry
	nil,                       // 12: oncell.hostagent.CreateCellRequest.SecretsEntry
}
var file_host_agent_proto_depIdxs = []int32{
	3,  // 0: oncell.hostagent.CellSpec.network:type_name -> oncell.hostagent.NetworkConfig
	2,  // 1: oncell.hostagent.CreateCellRequest.spec:type_name -> oncell.hostagent.CellSpec
	11, // 2: oncell.hostagent.CreateCellRequest.config:type_name -> oncell.hostagent.CreateCellRequest.ConfigEntry
	12, // 3: oncell.hostagent.CreateCellRequest.secrets:type_name -> oncell.hostagent.CreateCellRequest.SecretsEntry
	6,  // 4: oncell.hostagent.CellResponse.status:type_name -> oncell.hostagent.CellStatus
	7,  // 5: oncell.hostagent.CellStatus.resources:type_name -> oncell.hostagent.CellResourceUsage
	6,  // 6: oncell.hostagent.ListCellsResponse.cells:type_name -> oncell.hostagent.CellStatus
	4,  // 7: oncell.hostagent.HostAgent.CreateCell:input_type -> oncell.hostagent.CreateCellRequest
	1,  // 8: oncell.hostagent.HostAgent.StartCell:input_type -> oncell.hostagent.CellId
	1,  // 9: oncell.hostagent.HostAgent.PauseCell:input_type -> oncell.hostagent.CellId
	1,  // 10: oncell.hostagent.HostAgent.ResumeCell:input_type -> oncell.hostagent.CellId
	1,  // 11: oncell.hostagent.HostAgent.DeleteCell:input_type -> oncell.hostagent.CellId
	1,  // 12: oncell.hostagent.HostAgent.GetCellStatus:input_type -> oncell.hostagent.CellId
	1,  // 13: oncell.hostagent.HostAgent.SnapshotCell:input_type -> oncell.hostagent.CellId
	0,  // 14: oncell.hostagent.HostAgent.ListCells:input_type -> oncell.hostagent.Empty
	0,  // 15: oncell.hostagent.HostAgent.GetHostMetrics:input_type -> oncell.hostagent.Empty
	5,  // 16: oncell.hostagent.HostAgent.CreateCell:output_type -> oncell.hostagent.CellResponse
	5,  // 17: oncell.hostagent.HostAgent.StartCell:output_type -> oncell.hostagent.CellResponse
	5,  // 18: oncell.hostagent.HostAgent.PauseCell:output_type -> oncell.hostagent.CellResponse
	5,  // 19: oncell.hostagent.HostAgent.ResumeCell:output_type -> oncell.hostagent.CellResponse
	5,  // 20: oncell.hostagent.HostAgent.DeleteCell:output_type -> oncell.hostagent.CellResponse
	5,  // 21: oncell.hostagent.HostAgent.GetCellStatus:output_type -> oncell.hostagent.CellResponse
	8,  // 22: oncell.hostagent.HostAgent.SnapshotCell:output_type -> oncell.hostagent.SnapshotResponse
	9,  // 23: oncell.hostagent.HostAgent.ListCells:output_type -> oncell.hostagent.ListCellsResponse
	10, // 24: oncell.hostagent.HostAgent.GetHostMetrics:output_type -> oncell.hostagent.HostMetrics
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_host_agent_proto_init() }
func file_host_agent_proto_init() {
	if File_host_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_host_agent_proto_rawDesc), len(file_host_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_host_agent_proto_goTypes,
		DependencyIndexes: file_host_agent_proto_depIdxs,
		MessageInfos:      file_host_agent_proto_msgTypes,
	}.Build()
	File_host_agent_proto = out.File
	file_host_agent_proto_goTypes = nil
	file_host_agent_proto_depIdxs = nil
}
